from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, EmailStr
import os

from Vector_setup.services.email_service import _send_email

router = APIRouter()

CONTACT_RECIPIENT = os.getenv("CONTACT_RECIPIENT", "specisaac@gmail.com")



class ContactIn(BaseModel):
    name: str
    email: EmailStr
    subject: str
    message: str
    
@router.post("/contact")
def create_contact(payload: ContactIn):
    if not CONTACT_RECIPIENT:
        raise HTTPException(status_code=500, detail="Contact recipient not configured")
    
    subject = f"🚀 [CG Assistant] {payload.subject} from {payload.name}"
    
    # Process message for HTML line breaks
    message_html = payload.message.replace("\n", "<br/>")

    # Modern, Styled HTML Template
    html_body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 20px auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }}
            .header {{ background-color: #5850ec; color: #ffffff; padding: 20px; text-align: center; }}
            .content {{ padding: 30px; }}
            .field-label {{ font-weight: bold; color: #6b7280; text-transform: uppercase; font-size: 12px; margin-bottom: 4px; }}
            .field-value {{ margin-bottom: 20px; font-size: 16px; color: #111827; }}
            .message-box {{ background-color: #f9fafb; border-left: 4px solid #5850ec; padding: 15px; font-style: italic; }}
            .footer {{ background-color: #f3f4f6; padding: 15px; text-align: center; font-size: 12px; color: #9ca3af; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2 style="margin:0;">CG Assistant Lead</h2>
            </div>
            <div class="content">
                <div class="field-label">Sender Name</div>
                <div class="field-value">{payload.name}</div>

                <div class="field-label">Email Address</div>
                <div class="field-value"><a href="mailto:{payload.email}" style="color: #5850ec;">{payload.email}</a></div>

                <div class="field-label">Subject</div>
                <div class="field-value">{payload.subject}</div>

                <div class="field-label">Message</div>
                <div class="message-box">
                    {message_html}
                </div>
            </div>
            <div class="footer">
                This email was generated by the <strong>CG Assistant AI Platform</strong> Contact Form.
            </div>
        </div>
    </body>
    </html>
    """
    
    try:
        _send_email(CONTACT_RECIPIENT, subject, html_body)
    except Exception as e:
        print(f"Error: {e}") # Log the error for debugging
        raise HTTPException(status_code=500, detail="Could not send message")
    
    return {"detail": "Message sent"}